We dont use mongoid hence we removed it and updated active record ver…
NavigatingCancer/attribute_normalizer pull request #4
Opened 2022-12-13 16:24 UTC by ashwinisukale

…sion and ran test successfully

2022-12-14 16:23 UTC, surendra-nc approved these changes

2022-12-21 15:54 UTC, toppa requested changes
This looks good, but I think it should get a version bump. That way we don't have to worry about the current gc deployment inadvertently pulling in this version (and the current  gc Gemfile should probably be updated to point to the current version, if it doesn't already specify a version)

2023-01-06 10:26 UTC, ashwinisukale commented
@toppa thank you so much for your review, I have addressed the comment.

2023-01-06 14:52 UTC, toppa approved these changes
Looks good!

2023-03-14 15:58 UTC, merged